name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  deploy:
    runs-on: self-hosted

    steps:
    - name: Check if Docker Compose is running
      run: |
        cd /home/ubuntu/martin/docker_compose_ec2
        total_services=$(sudo docker compose config --services | wc -l)
        
        running_services=$(sudo docker compose ps | grep -c 'Up')
        
        if [ "$total_services" -eq "$running_services" ]; then
          echo "All services are running."
        else
          echo "Some services are not running. Starting all services..."
          sudo docker compose up -d
        fi
    - name: Pull latest Django backend image
      run: |
        cd /home/ubuntu/martin/docker_compose_ec2
        sudo docker compose pull django

    - name: Stop only the Django backend container
      run: |
        cd /home/ubuntu/martin/docker_compose_ec2
        sudo docker compose stop django

    - name: Start backend container with the latest image
      run: |
        cd /home/ubuntu/martin/docker_compose_ec2
        sudo docker compose up -d django

    - name: Remove unused Docker images 
      run: |
        sudo docker image prune -af

    - name: Show active containers
      run: |
        sudo docker container ls
